### ISSUE TITLE
index.js 'use strict' problem

### ISSUE THREAD

**Issue by MKRoughDiamond** [sonowz/graduate-adventure#57]
Of course, when we use js, we should use `use strict`. But when we put it in our `index.js` file, Compile error(cannot find 'Elm') occurs.
So, I commented this line. If I find other way that has no error with `use strict`, I'll rewrite it.

**Comment by sonowz** [comment]
Actually it is a 'runtime error' rather than 'compile error'.

**Comment by MKRoughDiamond** [comment]
It's my mistake :D

**Comment by sonowz** [comment]
I'm no expert in JavaScript, but I think `var Elm = ` [here](https://github.com/LastOne817/graduate-adventure/blob/master/frontend/src/static/index.js) shadows(or overrides) `Elm` in global scope, so that `filerequest.js` cannot reference `Elm` variable.
So unless we find a way to explicitly say `Elm` is a global variable, we shouldn't use `use strict` directive.
Current solution is to remove `use strict` and just use `Elm =`.

**Comment by MKRoughDiamond** [comment]
Are functions and variables that come after `use strict` statement local?

**Comment by sonowz** [comment]
https://www.w3schools.com/js/js_strict.asp
You cannot use undeclared variables if you write `use strict`.

**Comment by sonowz** [comment]
I think this issue was solved, so closing. @MKRoughDiamond
